// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dut_digitrec_HH_
#define _dut_digitrec_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "dut_knn_vote.h"
#include "dut_update_knn.h"
#include "dut_digitrec_training_data_V.h"
#include "dut_digitrec_knn_set_V.h"

namespace ap_rtl {

struct dut_digitrec : public sc_module {
    // Port declarations 8
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<49> > input_V;
    sc_out< sc_lv<4> > ap_return;


    // Module declarations
    dut_digitrec(sc_module_name name);
    SC_HAS_PROCESS(dut_digitrec);

    ~dut_digitrec();

    sc_trace_file* mVcdFile;

    dut_digitrec_training_data_V* training_data_V_U;
    dut_digitrec_knn_set_V* knn_set_V_U;
    dut_knn_vote* grp_dut_knn_vote_fu_148;
    dut_update_knn* grp_dut_update_knn_fu_153;
    sc_signal< sc_lv<8> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_25;
    sc_signal< sc_lv<15> > training_data_V_address0;
    sc_signal< sc_logic > training_data_V_ce0;
    sc_signal< sc_lv<48> > training_data_V_q0;
    sc_signal< sc_lv<4> > i_5_fu_169_p2;
    sc_signal< sc_lv<4> > i_5_reg_271;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_51;
    sc_signal< sc_lv<6> > tmp_23_fu_187_p2;
    sc_signal< sc_lv<6> > tmp_23_reg_276;
    sc_signal< sc_lv<1> > exitcond7_fu_163_p2;
    sc_signal< sc_lv<2> > k_3_fu_199_p2;
    sc_signal< sc_logic > ap_sig_cseq_ST_st3_fsm_2;
    sc_signal< bool > ap_sig_66;
    sc_signal< sc_lv<11> > i_6_fu_225_p2;
    sc_signal< sc_lv<11> > i_6_reg_292;
    sc_signal< sc_logic > ap_sig_cseq_ST_st4_fsm_3;
    sc_signal< bool > ap_sig_75;
    sc_signal< sc_lv<15> > tmp_cast_19_fu_231_p1;
    sc_signal< sc_lv<15> > tmp_cast_19_reg_297;
    sc_signal< sc_lv<1> > exitcond8_fu_219_p2;
    sc_signal< sc_lv<4> > j_2_fu_241_p2;
    sc_signal< sc_lv<4> > j_2_reg_305;
    sc_signal< sc_logic > ap_sig_cseq_ST_st5_fsm_4;
    sc_signal< bool > ap_sig_89;
    sc_signal< sc_lv<15> > next_mul_fu_247_p2;
    sc_signal< sc_lv<15> > next_mul_reg_310;
    sc_signal< sc_lv<1> > exitcond_fu_235_p2;
    sc_signal< sc_lv<48> > training_instance_V_reg_320;
    sc_signal< sc_logic > ap_sig_cseq_ST_st6_fsm_5;
    sc_signal< bool > ap_sig_104;
    sc_signal< sc_lv<5> > knn_set_V_address0;
    sc_signal< sc_logic > knn_set_V_ce0;
    sc_signal< sc_logic > knn_set_V_we0;
    sc_signal< sc_lv<6> > knn_set_V_d0;
    sc_signal< sc_lv<6> > knn_set_V_q0;
    sc_signal< sc_logic > grp_dut_knn_vote_fu_148_ap_start;
    sc_signal< sc_logic > grp_dut_knn_vote_fu_148_ap_done;
    sc_signal< sc_logic > grp_dut_knn_vote_fu_148_ap_idle;
    sc_signal< sc_logic > grp_dut_knn_vote_fu_148_ap_ready;
    sc_signal< sc_lv<5> > grp_dut_knn_vote_fu_148_knn_set_V_address0;
    sc_signal< sc_logic > grp_dut_knn_vote_fu_148_knn_set_V_ce0;
    sc_signal< sc_lv<4> > grp_dut_knn_vote_fu_148_ap_return;
    sc_signal< sc_logic > grp_dut_update_knn_fu_153_ap_start;
    sc_signal< sc_logic > grp_dut_update_knn_fu_153_ap_done;
    sc_signal< sc_logic > grp_dut_update_knn_fu_153_ap_idle;
    sc_signal< sc_logic > grp_dut_update_knn_fu_153_ap_ready;
    sc_signal< sc_lv<5> > grp_dut_update_knn_fu_153_min_distances_V_address0;
    sc_signal< sc_logic > grp_dut_update_knn_fu_153_min_distances_V_ce0;
    sc_signal< sc_logic > grp_dut_update_knn_fu_153_min_distances_V_we0;
    sc_signal< sc_lv<6> > grp_dut_update_knn_fu_153_min_distances_V_d0;
    sc_signal< sc_lv<4> > i_reg_92;
    sc_signal< sc_lv<1> > exitcond9_fu_193_p2;
    sc_signal< sc_lv<2> > k_reg_103;
    sc_signal< sc_lv<11> > i4_reg_114;
    sc_signal< sc_lv<4> > j_reg_125;
    sc_signal< sc_logic > ap_sig_cseq_ST_st7_fsm_6;
    sc_signal< bool > ap_sig_165;
    sc_signal< sc_lv<15> > phi_mul_reg_137;
    sc_signal< sc_logic > ap_reg_grp_dut_knn_vote_fu_148_ap_start;
    sc_signal< sc_logic > ap_sig_cseq_ST_st8_fsm_7;
    sc_signal< bool > ap_sig_182;
    sc_signal< sc_logic > ap_reg_grp_dut_update_knn_fu_153_ap_start;
    sc_signal< sc_lv<64> > tmp_32_cast_fu_214_p1;
    sc_signal< sc_lv<64> > tmp_34_cast_fu_258_p1;
    sc_signal< sc_lv<6> > tmp_s_fu_179_p3;
    sc_signal< sc_lv<6> > tmp_cast_fu_175_p1;
    sc_signal< sc_lv<6> > tmp_28_cast_fu_205_p1;
    sc_signal< sc_lv<6> > tmp_25_fu_209_p2;
    sc_signal< sc_lv<15> > tmp_26_fu_253_p2;
    sc_signal< sc_lv<4> > ap_return_preg;
    sc_signal< sc_lv<8> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<8> ap_ST_st1_fsm_0;
    static const sc_lv<8> ap_ST_st2_fsm_1;
    static const sc_lv<8> ap_ST_st3_fsm_2;
    static const sc_lv<8> ap_ST_st4_fsm_3;
    static const sc_lv<8> ap_ST_st5_fsm_4;
    static const sc_lv<8> ap_ST_st6_fsm_5;
    static const sc_lv<8> ap_ST_st7_fsm_6;
    static const sc_lv<8> ap_ST_st8_fsm_7;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<11> ap_const_lv11_0;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<15> ap_const_lv15_0;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<6> ap_const_lv6_32;
    static const sc_lv<4> ap_const_lv4_A;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<11> ap_const_lv11_708;
    static const sc_lv<11> ap_const_lv11_1;
    static const sc_lv<15> ap_const_lv15_708;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_ap_sig_104();
    void thread_ap_sig_165();
    void thread_ap_sig_182();
    void thread_ap_sig_25();
    void thread_ap_sig_51();
    void thread_ap_sig_66();
    void thread_ap_sig_75();
    void thread_ap_sig_89();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_ap_sig_cseq_ST_st3_fsm_2();
    void thread_ap_sig_cseq_ST_st4_fsm_3();
    void thread_ap_sig_cseq_ST_st5_fsm_4();
    void thread_ap_sig_cseq_ST_st6_fsm_5();
    void thread_ap_sig_cseq_ST_st7_fsm_6();
    void thread_ap_sig_cseq_ST_st8_fsm_7();
    void thread_exitcond7_fu_163_p2();
    void thread_exitcond8_fu_219_p2();
    void thread_exitcond9_fu_193_p2();
    void thread_exitcond_fu_235_p2();
    void thread_grp_dut_knn_vote_fu_148_ap_start();
    void thread_grp_dut_update_knn_fu_153_ap_start();
    void thread_i_5_fu_169_p2();
    void thread_i_6_fu_225_p2();
    void thread_j_2_fu_241_p2();
    void thread_k_3_fu_199_p2();
    void thread_knn_set_V_address0();
    void thread_knn_set_V_ce0();
    void thread_knn_set_V_d0();
    void thread_knn_set_V_we0();
    void thread_next_mul_fu_247_p2();
    void thread_tmp_23_fu_187_p2();
    void thread_tmp_25_fu_209_p2();
    void thread_tmp_26_fu_253_p2();
    void thread_tmp_28_cast_fu_205_p1();
    void thread_tmp_32_cast_fu_214_p1();
    void thread_tmp_34_cast_fu_258_p1();
    void thread_tmp_cast_19_fu_231_p1();
    void thread_tmp_cast_fu_175_p1();
    void thread_tmp_s_fu_179_p3();
    void thread_training_data_V_address0();
    void thread_training_data_V_ce0();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
