// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dut_knn_vote.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dut_knn_vote::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dut_knn_vote::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<11> dut_knn_vote::ap_ST_st1_fsm_0 = "1";
const sc_lv<11> dut_knn_vote::ap_ST_st2_fsm_1 = "10";
const sc_lv<11> dut_knn_vote::ap_ST_st3_fsm_2 = "100";
const sc_lv<11> dut_knn_vote::ap_ST_st4_fsm_3 = "1000";
const sc_lv<11> dut_knn_vote::ap_ST_st5_fsm_4 = "10000";
const sc_lv<11> dut_knn_vote::ap_ST_st6_fsm_5 = "100000";
const sc_lv<11> dut_knn_vote::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<11> dut_knn_vote::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<11> dut_knn_vote::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<11> dut_knn_vote::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<11> dut_knn_vote::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<32> dut_knn_vote::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> dut_knn_vote::ap_const_lv1_1 = "1";
const sc_lv<32> dut_knn_vote::ap_const_lv32_1 = "1";
const sc_lv<32> dut_knn_vote::ap_const_lv32_2 = "10";
const sc_lv<1> dut_knn_vote::ap_const_lv1_0 = "0";
const sc_lv<32> dut_knn_vote::ap_const_lv32_3 = "11";
const sc_lv<32> dut_knn_vote::ap_const_lv32_4 = "100";
const sc_lv<32> dut_knn_vote::ap_const_lv32_6 = "110";
const sc_lv<32> dut_knn_vote::ap_const_lv32_7 = "111";
const sc_lv<32> dut_knn_vote::ap_const_lv32_9 = "1001";
const sc_lv<32> dut_knn_vote::ap_const_lv32_A = "1010";
const sc_lv<2> dut_knn_vote::ap_const_lv2_0 = "00";
const sc_lv<4> dut_knn_vote::ap_const_lv4_0 = "0000";
const sc_lv<32> dut_knn_vote::ap_const_lv32_5 = "101";
const sc_lv<32> dut_knn_vote::ap_const_lv32_8 = "1000";
const sc_lv<6> dut_knn_vote::ap_const_lv6_0 = "000000";
const sc_lv<6> dut_knn_vote::ap_const_lv6_32 = "110010";
const sc_lv<4> dut_knn_vote::ap_const_lv4_1 = "1";
const sc_lv<2> dut_knn_vote::ap_const_lv2_3 = "11";
const sc_lv<2> dut_knn_vote::ap_const_lv2_1 = "1";
const sc_lv<4> dut_knn_vote::ap_const_lv4_A = "1010";
const sc_lv<2> dut_knn_vote::ap_const_lv2_2 = "10";

dut_knn_vote::dut_knn_vote(sc_module_name name) : sc_module(name), mVcdFile(0) {
    votes_V_U = new dut_knn_vote_votes_V("votes_V_U");
    votes_V_U->clk(ap_clk);
    votes_V_U->reset(ap_rst);
    votes_V_U->address0(votes_V_address0);
    votes_V_U->ce0(votes_V_ce0);
    votes_V_U->we0(votes_V_we0);
    votes_V_U->d0(votes_V_d0);
    votes_V_U->q0(votes_V_q0);
    votes_V_U->address1(votes_V_address1);
    votes_V_U->ce1(votes_V_ce1);
    votes_V_U->q1(votes_V_q1);
    dut_mux_3to1_sel2_6_1_U5 = new dut_mux_3to1_sel2_6_1<1,1,6,6,6,2,6>("dut_mux_3to1_sel2_6_1_U5");
    dut_mux_3to1_sel2_6_1_U5->din1(min_distances_2_V_3_fu_78);
    dut_mux_3to1_sel2_6_1_U5->din2(min_distances_2_V_4_fu_82);
    dut_mux_3to1_sel2_6_1_U5->din3(min_distances_2_V_2_fu_86);
    dut_mux_3to1_sel2_6_1_U5->din4(k2_reg_183);
    dut_mux_3to1_sel2_6_1_U5->dout(tmp_3_fu_464_p5);
    dut_mux_3to1_sel2_4_1_U6 = new dut_mux_3to1_sel2_4_1<1,1,4,4,4,2,4>("dut_mux_3to1_sel2_4_1_U6");
    dut_mux_3to1_sel2_4_1_U6->din1(voters_2_V_1_fu_90);
    dut_mux_3to1_sel2_4_1_U6->din2(voters_2_V_2_fu_94);
    dut_mux_3to1_sel2_4_1_U6->din3(voters_2_V_7_fu_98);
    dut_mux_3to1_sel2_4_1_U6->din4(i5_reg_228);
    dut_mux_3to1_sel2_4_1_U6->dout(tmp_1_fu_731_p5);
    dut_mux_3to1_sel2_6_1_U7 = new dut_mux_3to1_sel2_6_1<1,1,6,6,6,2,6>("dut_mux_3to1_sel2_6_1_U7");
    dut_mux_3to1_sel2_6_1_U7->din1(min_distances_2_V_3_fu_78);
    dut_mux_3to1_sel2_6_1_U7->din2(min_distances_2_V_4_fu_82);
    dut_mux_3to1_sel2_6_1_U7->din3(min_distances_2_V_2_fu_86);
    dut_mux_3to1_sel2_6_1_U7->din4(i5_reg_228);
    dut_mux_3to1_sel2_6_1_U7->dout(min_dist_V_fu_748_p5);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( exitcond_fu_797_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( exitcond_fu_797_p2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( exitcond_fu_797_p2 );
    sensitive << ( agg_result_V_reg_239 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_ap_sig_103);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_125);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_141);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_189);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_205);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_28);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_47);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_56);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_71);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_85);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_94);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st10_fsm_9);
    sensitive << ( ap_sig_125 );

    SC_METHOD(thread_ap_sig_cseq_ST_st11_fsm_10);
    sensitive << ( ap_sig_141 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_28 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_47 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_56 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_71 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_85 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_189 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_94 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_103 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_8);
    sensitive << ( ap_sig_205 );

    SC_METHOD(thread_cond_fu_482_p2);
    sensitive << ( k2_reg_183 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_exitcond1_fu_302_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( k_reg_149 );

    SC_METHOD(thread_exitcond2_fu_396_p2);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( voters_1_V_reg_160 );

    SC_METHOD(thread_exitcond3_fu_702_p2);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( i4_reg_195 );

    SC_METHOD(thread_exitcond4_fu_426_p2);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( j_reg_172 );

    SC_METHOD(thread_exitcond5_fu_719_p2);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( i5_reg_228 );

    SC_METHOD(thread_exitcond6_fu_452_p2);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( k2_reg_183 );

    SC_METHOD(thread_exitcond_fu_797_p2);
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( result_V_reg_263 );

    SC_METHOD(thread_i_3_fu_402_p2);
    sensitive << ( voters_1_V_reg_160 );

    SC_METHOD(thread_i_4_fu_725_p2);
    sensitive << ( i5_reg_228 );

    SC_METHOD(thread_i_V_fu_892_p2);
    sensitive << ( result_V_reg_263 );

    SC_METHOD(thread_i_fu_708_p2);
    sensitive << ( i4_reg_195 );

    SC_METHOD(thread_j_1_fu_432_p2);
    sensitive << ( j_reg_172 );

    SC_METHOD(thread_k_1_fu_308_p2);
    sensitive << ( k_reg_149 );

    SC_METHOD(thread_k_2_fu_458_p2);
    sensitive << ( k2_reg_183 );

    SC_METHOD(thread_knn_set_V_address0);
    sensitive << ( knn_set_V_addr_reg_984 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_knn_set_V_ce0);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_min_distances_0_V_1_fu_358_p3);
    sensitive << ( min_distances_0_V_fu_62 );
    sensitive << ( sel_tmp6_fu_328_p2 );

    SC_METHOD(thread_min_distances_1_V_1_fu_350_p3);
    sensitive << ( min_distances_1_V_fu_66 );
    sensitive << ( sel_tmp6_fu_328_p2 );
    sensitive << ( sel_tmp9_fu_342_p3 );

    SC_METHOD(thread_min_distances_2_V_11_fu_598_p3);
    sensitive << ( knn_set_V_q0 );
    sensitive << ( min_distances_2_V_3_fu_78 );
    sensitive << ( cond_fu_482_p2 );

    SC_METHOD(thread_min_distances_2_V_12_fu_656_p3);
    sensitive << ( min_distances_2_V_4_fu_82 );
    sensitive << ( sel_tmp8_fu_618_p2 );
    sensitive << ( min_distances_2_V_7_fu_590_p3 );

    SC_METHOD(thread_min_distances_2_V_13_fu_664_p3);
    sensitive << ( min_distances_2_V_3_fu_78 );
    sensitive << ( sel_tmp8_fu_618_p2 );
    sensitive << ( min_distances_2_V_11_fu_598_p3 );

    SC_METHOD(thread_min_distances_2_V_1_fu_334_p3);
    sensitive << ( min_distances_2_V_fu_70 );
    sensitive << ( sel_tmp6_fu_328_p2 );
    sensitive << ( sel_tmp5_fu_320_p3 );

    SC_METHOD(thread_min_distances_2_V_5_fu_574_p3);
    sensitive << ( min_distances_2_V_2_fu_86 );
    sensitive << ( cond_fu_482_p2 );
    sensitive << ( min_distances_2_V_8_fu_566_p3 );

    SC_METHOD(thread_min_distances_2_V_6_fu_648_p3);
    sensitive << ( min_distances_2_V_2_fu_86 );
    sensitive << ( sel_tmp8_fu_618_p2 );
    sensitive << ( min_distances_2_V_5_fu_574_p3 );

    SC_METHOD(thread_min_distances_2_V_7_fu_590_p3);
    sensitive << ( min_distances_2_V_4_fu_82 );
    sensitive << ( cond_fu_482_p2 );
    sensitive << ( min_distances_2_V_9_fu_582_p3 );

    SC_METHOD(thread_min_distances_2_V_8_fu_566_p3);
    sensitive << ( knn_set_V_q0 );
    sensitive << ( min_distances_2_V_2_fu_86 );
    sensitive << ( sel_tmp1_fu_520_p2 );

    SC_METHOD(thread_min_distances_2_V_9_fu_582_p3);
    sensitive << ( knn_set_V_q0 );
    sensitive << ( min_distances_2_V_4_fu_82 );
    sensitive << ( sel_tmp1_fu_520_p2 );

    SC_METHOD(thread_min_distances_V_load_phi_fu_488_p3);
    sensitive << ( min_distances_2_V_4_fu_82 );
    sensitive << ( min_distances_2_V_2_fu_86 );
    sensitive << ( cond_fu_482_p2 );

    SC_METHOD(thread_min_voter_V_fu_766_p1);
    sensitive << ( tmp_1_fu_731_p5 );

    SC_METHOD(thread_min_voter_V_s_fu_770_p3);
    sensitive << ( p_s_reg_206 );
    sensitive << ( tmp_12_fu_760_p2 );
    sensitive << ( min_voter_V_fu_766_p1 );

    SC_METHOD(thread_or_cond_fu_612_p2);
    sensitive << ( tmp_fu_606_p2 );
    sensitive << ( rev_fu_502_p2 );

    SC_METHOD(thread_p_1_14_fu_778_p3);
    sensitive << ( p_1_reg_217 );
    sensitive << ( min_dist_V_fu_748_p5 );
    sensitive << ( tmp_12_fu_760_p2 );

    SC_METHOD(thread_p_2_agg_result_V_fu_834_p3);
    sensitive << ( tmp_22_reg_1046 );
    sensitive << ( agg_result_V_reg_239 );
    sensitive << ( result_V_reg_263 );

    SC_METHOD(thread_p_2_agg_result_V_load_fu_841_p3);
    sensitive << ( tmp_22_reg_1046 );
    sensitive << ( agg_result_V_load_reg_251 );
    sensitive << ( result_V_reg_263 );

    SC_METHOD(thread_result_V_1_fu_848_p3);
    sensitive << ( agg_result_V_reg_239 );
    sensitive << ( result_V_reg_263 );
    sensitive << ( tmp_17_fu_822_p2 );

    SC_METHOD(thread_result_V_2_fu_868_p3);
    sensitive << ( sel_tmp3_fu_862_p2 );
    sensitive << ( p_2_agg_result_V_fu_834_p3 );
    sensitive << ( result_V_1_fu_848_p3 );

    SC_METHOD(thread_result_V_3_fu_876_p3);
    sensitive << ( agg_result_V_load_reg_251 );
    sensitive << ( result_V_reg_263 );
    sensitive << ( tmp_17_fu_822_p2 );

    SC_METHOD(thread_result_V_4_fu_884_p3);
    sensitive << ( sel_tmp3_fu_862_p2 );
    sensitive << ( p_2_agg_result_V_load_fu_841_p3 );
    sensitive << ( result_V_3_fu_876_p3 );

    SC_METHOD(thread_rev_fu_502_p2);
    sensitive << ( ult_fu_496_p2 );

    SC_METHOD(thread_sel_tmp1_fu_520_p2);
    sensitive << ( k2_reg_183 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_sel_tmp2_fu_856_p2);
    sensitive << ( tmp_17_fu_822_p2 );

    SC_METHOD(thread_sel_tmp3_fu_862_p2);
    sensitive << ( tmp_19_fu_828_p2 );
    sensitive << ( sel_tmp2_fu_856_p2 );

    SC_METHOD(thread_sel_tmp5_fu_320_p3);
    sensitive << ( min_distances_2_V_fu_70 );
    sensitive << ( sel_tmp_fu_314_p2 );

    SC_METHOD(thread_sel_tmp6_fu_328_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( k_reg_149 );
    sensitive << ( exitcond1_fu_302_p2 );

    SC_METHOD(thread_sel_tmp8_fu_618_p2);
    sensitive << ( tmp_18_fu_476_p2 );
    sensitive << ( or_cond_fu_612_p2 );

    SC_METHOD(thread_sel_tmp9_fu_342_p3);
    sensitive << ( min_distances_1_V_fu_66 );
    sensitive << ( sel_tmp_fu_314_p2 );

    SC_METHOD(thread_sel_tmp_fu_314_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( k_reg_149 );
    sensitive << ( exitcond1_fu_302_p2 );

    SC_METHOD(thread_tmp_10_fu_743_p1);
    sensitive << ( tmp_1_fu_731_p5 );

    SC_METHOD(thread_tmp_11_fu_790_p2);
    sensitive << ( votes_V_q0 );

    SC_METHOD(thread_tmp_12_fu_760_p2);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( exitcond5_fu_719_p2 );
    sensitive << ( p_1_reg_217 );
    sensitive << ( min_dist_V_fu_748_p5 );

    SC_METHOD(thread_tmp_14_cast_fu_438_p1);
    sensitive << ( j_reg_172 );

    SC_METHOD(thread_tmp_14_fu_442_p2);
    sensitive << ( tmp_8_reg_971 );
    sensitive << ( tmp_14_cast_fu_438_p1 );

    SC_METHOD(thread_tmp_15_cast_fu_786_p1);
    sensitive << ( p_s_reg_206 );

    SC_METHOD(thread_tmp_15_fu_803_p1);
    sensitive << ( result_V_reg_263 );

    SC_METHOD(thread_tmp_16_fu_808_p1);
    sensitive << ( agg_result_V_load_reg_251 );

    SC_METHOD(thread_tmp_17_fu_822_p2);
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( votes_V_q0 );
    sensitive << ( votes_V_q1 );

    SC_METHOD(thread_tmp_18_fu_476_p2);
    sensitive << ( knn_set_V_q0 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( tmp_3_fu_464_p5 );

    SC_METHOD(thread_tmp_19_fu_828_p2);
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( votes_V_q0 );
    sensitive << ( votes_V_q1 );

    SC_METHOD(thread_tmp_20_fu_508_p2);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( tmp_3_fu_464_p5 );

    SC_METHOD(thread_tmp_21_fu_514_p2);
    sensitive << ( k2_reg_183 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_tmp_22_fu_817_p2);
    sensitive << ( tmp_15_cast_reg_1028 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( exitcond_fu_797_p2 );
    sensitive << ( tmp_30_cast_fu_813_p1 );

    SC_METHOD(thread_tmp_29_cast_fu_447_p1);
    sensitive << ( tmp_14_fu_442_p2 );

    SC_METHOD(thread_tmp_30_cast_fu_813_p1);
    sensitive << ( result_V_reg_263 );

    SC_METHOD(thread_tmp_7_fu_412_p3);
    sensitive << ( voters_1_V_reg_160 );

    SC_METHOD(thread_tmp_8_fu_420_p2);
    sensitive << ( tmp_7_fu_412_p3 );
    sensitive << ( tmp_cast_fu_408_p1 );

    SC_METHOD(thread_tmp_9_fu_714_p1);
    sensitive << ( i4_reg_195 );

    SC_METHOD(thread_tmp_cast_fu_408_p1);
    sensitive << ( voters_1_V_reg_160 );

    SC_METHOD(thread_tmp_fu_606_p2);
    sensitive << ( tmp_20_fu_508_p2 );
    sensitive << ( tmp_21_fu_514_p2 );

    SC_METHOD(thread_ult_fu_496_p2);
    sensitive << ( knn_set_V_q0 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( min_distances_V_load_phi_fu_488_p3 );

    SC_METHOD(thread_voters_2_V_12_fu_640_p3);
    sensitive << ( voters_2_V_1_fu_90 );
    sensitive << ( sel_tmp8_fu_618_p2 );
    sensitive << ( voters_2_V_8_fu_558_p3 );

    SC_METHOD(thread_voters_2_V_3_fu_534_p3);
    sensitive << ( voters_2_V_7_fu_98 );
    sensitive << ( cond_fu_482_p2 );
    sensitive << ( voters_2_V_fu_526_p3 );

    SC_METHOD(thread_voters_2_V_4_fu_624_p3);
    sensitive << ( voters_2_V_7_fu_98 );
    sensitive << ( sel_tmp8_fu_618_p2 );
    sensitive << ( voters_2_V_3_fu_534_p3 );

    SC_METHOD(thread_voters_2_V_5_fu_542_p3);
    sensitive << ( voters_1_V_reg_160 );
    sensitive << ( voters_2_V_2_fu_94 );
    sensitive << ( sel_tmp1_fu_520_p2 );

    SC_METHOD(thread_voters_2_V_6_fu_550_p3);
    sensitive << ( voters_2_V_2_fu_94 );
    sensitive << ( cond_fu_482_p2 );
    sensitive << ( voters_2_V_5_fu_542_p3 );

    SC_METHOD(thread_voters_2_V_8_fu_558_p3);
    sensitive << ( voters_1_V_reg_160 );
    sensitive << ( voters_2_V_1_fu_90 );
    sensitive << ( cond_fu_482_p2 );

    SC_METHOD(thread_voters_2_V_9_fu_632_p3);
    sensitive << ( voters_2_V_2_fu_94 );
    sensitive << ( sel_tmp8_fu_618_p2 );
    sensitive << ( voters_2_V_6_fu_550_p3 );

    SC_METHOD(thread_voters_2_V_fu_526_p3);
    sensitive << ( voters_1_V_reg_160 );
    sensitive << ( voters_2_V_7_fu_98 );
    sensitive << ( sel_tmp1_fu_520_p2 );

    SC_METHOD(thread_votes_V_address0);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( votes_V_addr_1_reg_1013 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( tmp_9_fu_714_p1 );
    sensitive << ( tmp_10_fu_743_p1 );
    sensitive << ( tmp_15_fu_803_p1 );

    SC_METHOD(thread_votes_V_address1);
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( tmp_16_fu_808_p1 );

    SC_METHOD(thread_votes_V_ce0);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );

    SC_METHOD(thread_votes_V_ce1);
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );

    SC_METHOD(thread_votes_V_d0);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( tmp_11_fu_790_p2 );

    SC_METHOD(thread_votes_V_we0);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( exitcond3_fu_702_p2 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond2_fu_396_p2 );
    sensitive << ( exitcond4_fu_426_p2 );
    sensitive << ( exitcond5_fu_719_p2 );
    sensitive << ( exitcond_fu_797_p2 );
    sensitive << ( exitcond1_fu_302_p2 );
    sensitive << ( exitcond6_fu_452_p2 );
    sensitive << ( exitcond3_fu_702_p2 );

    ap_CS_fsm = "00000000001";
    ap_return_preg = "0000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dut_knn_vote_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, knn_set_V_address0, "(port)knn_set_V_address0");
    sc_trace(mVcdFile, knn_set_V_ce0, "(port)knn_set_V_ce0");
    sc_trace(mVcdFile, knn_set_V_q0, "(port)knn_set_V_q0");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_28, "ap_sig_28");
    sc_trace(mVcdFile, k_1_fu_308_p2, "k_1_fu_308_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_47, "ap_sig_47");
    sc_trace(mVcdFile, i_3_fu_402_p2, "i_3_fu_402_p2");
    sc_trace(mVcdFile, i_3_reg_966, "i_3_reg_966");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_56, "ap_sig_56");
    sc_trace(mVcdFile, tmp_8_fu_420_p2, "tmp_8_fu_420_p2");
    sc_trace(mVcdFile, tmp_8_reg_971, "tmp_8_reg_971");
    sc_trace(mVcdFile, exitcond2_fu_396_p2, "exitcond2_fu_396_p2");
    sc_trace(mVcdFile, j_1_fu_432_p2, "j_1_fu_432_p2");
    sc_trace(mVcdFile, j_1_reg_979, "j_1_reg_979");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_71, "ap_sig_71");
    sc_trace(mVcdFile, knn_set_V_addr_reg_984, "knn_set_V_addr_reg_984");
    sc_trace(mVcdFile, exitcond4_fu_426_p2, "exitcond4_fu_426_p2");
    sc_trace(mVcdFile, k_2_fu_458_p2, "k_2_fu_458_p2");
    sc_trace(mVcdFile, k_2_reg_992, "k_2_reg_992");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_85, "ap_sig_85");
    sc_trace(mVcdFile, i_fu_708_p2, "i_fu_708_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_94, "ap_sig_94");
    sc_trace(mVcdFile, i_4_fu_725_p2, "i_4_fu_725_p2");
    sc_trace(mVcdFile, i_4_reg_1008, "i_4_reg_1008");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_103, "ap_sig_103");
    sc_trace(mVcdFile, votes_V_addr_1_reg_1013, "votes_V_addr_1_reg_1013");
    sc_trace(mVcdFile, exitcond5_fu_719_p2, "exitcond5_fu_719_p2");
    sc_trace(mVcdFile, min_voter_V_s_fu_770_p3, "min_voter_V_s_fu_770_p3");
    sc_trace(mVcdFile, min_voter_V_s_reg_1018, "min_voter_V_s_reg_1018");
    sc_trace(mVcdFile, p_1_14_fu_778_p3, "p_1_14_fu_778_p3");
    sc_trace(mVcdFile, p_1_14_reg_1023, "p_1_14_reg_1023");
    sc_trace(mVcdFile, tmp_15_cast_fu_786_p1, "tmp_15_cast_fu_786_p1");
    sc_trace(mVcdFile, tmp_15_cast_reg_1028, "tmp_15_cast_reg_1028");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st10_fsm_9, "ap_sig_cseq_ST_st10_fsm_9");
    sc_trace(mVcdFile, ap_sig_125, "ap_sig_125");
    sc_trace(mVcdFile, exitcond_fu_797_p2, "exitcond_fu_797_p2");
    sc_trace(mVcdFile, tmp_22_fu_817_p2, "tmp_22_fu_817_p2");
    sc_trace(mVcdFile, tmp_22_reg_1046, "tmp_22_reg_1046");
    sc_trace(mVcdFile, result_V_2_fu_868_p3, "result_V_2_fu_868_p3");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st11_fsm_10, "ap_sig_cseq_ST_st11_fsm_10");
    sc_trace(mVcdFile, ap_sig_141, "ap_sig_141");
    sc_trace(mVcdFile, result_V_4_fu_884_p3, "result_V_4_fu_884_p3");
    sc_trace(mVcdFile, i_V_fu_892_p2, "i_V_fu_892_p2");
    sc_trace(mVcdFile, votes_V_address0, "votes_V_address0");
    sc_trace(mVcdFile, votes_V_ce0, "votes_V_ce0");
    sc_trace(mVcdFile, votes_V_we0, "votes_V_we0");
    sc_trace(mVcdFile, votes_V_d0, "votes_V_d0");
    sc_trace(mVcdFile, votes_V_q0, "votes_V_q0");
    sc_trace(mVcdFile, votes_V_address1, "votes_V_address1");
    sc_trace(mVcdFile, votes_V_ce1, "votes_V_ce1");
    sc_trace(mVcdFile, votes_V_q1, "votes_V_q1");
    sc_trace(mVcdFile, k_reg_149, "k_reg_149");
    sc_trace(mVcdFile, exitcond1_fu_302_p2, "exitcond1_fu_302_p2");
    sc_trace(mVcdFile, voters_1_V_reg_160, "voters_1_V_reg_160");
    sc_trace(mVcdFile, j_reg_172, "j_reg_172");
    sc_trace(mVcdFile, exitcond6_fu_452_p2, "exitcond6_fu_452_p2");
    sc_trace(mVcdFile, k2_reg_183, "k2_reg_183");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_189, "ap_sig_189");
    sc_trace(mVcdFile, i4_reg_195, "i4_reg_195");
    sc_trace(mVcdFile, exitcond3_fu_702_p2, "exitcond3_fu_702_p2");
    sc_trace(mVcdFile, p_s_reg_206, "p_s_reg_206");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_8, "ap_sig_cseq_ST_st9_fsm_8");
    sc_trace(mVcdFile, ap_sig_205, "ap_sig_205");
    sc_trace(mVcdFile, p_1_reg_217, "p_1_reg_217");
    sc_trace(mVcdFile, i5_reg_228, "i5_reg_228");
    sc_trace(mVcdFile, agg_result_V_reg_239, "agg_result_V_reg_239");
    sc_trace(mVcdFile, agg_result_V_load_reg_251, "agg_result_V_load_reg_251");
    sc_trace(mVcdFile, result_V_reg_263, "result_V_reg_263");
    sc_trace(mVcdFile, tmp_29_cast_fu_447_p1, "tmp_29_cast_fu_447_p1");
    sc_trace(mVcdFile, tmp_9_fu_714_p1, "tmp_9_fu_714_p1");
    sc_trace(mVcdFile, tmp_10_fu_743_p1, "tmp_10_fu_743_p1");
    sc_trace(mVcdFile, tmp_15_fu_803_p1, "tmp_15_fu_803_p1");
    sc_trace(mVcdFile, tmp_16_fu_808_p1, "tmp_16_fu_808_p1");
    sc_trace(mVcdFile, min_distances_0_V_fu_62, "min_distances_0_V_fu_62");
    sc_trace(mVcdFile, min_distances_0_V_1_fu_358_p3, "min_distances_0_V_1_fu_358_p3");
    sc_trace(mVcdFile, min_distances_1_V_fu_66, "min_distances_1_V_fu_66");
    sc_trace(mVcdFile, min_distances_1_V_1_fu_350_p3, "min_distances_1_V_1_fu_350_p3");
    sc_trace(mVcdFile, min_distances_2_V_fu_70, "min_distances_2_V_fu_70");
    sc_trace(mVcdFile, min_distances_2_V_1_fu_334_p3, "min_distances_2_V_1_fu_334_p3");
    sc_trace(mVcdFile, min_distances_2_V_3_fu_78, "min_distances_2_V_3_fu_78");
    sc_trace(mVcdFile, min_distances_2_V_13_fu_664_p3, "min_distances_2_V_13_fu_664_p3");
    sc_trace(mVcdFile, min_distances_2_V_4_fu_82, "min_distances_2_V_4_fu_82");
    sc_trace(mVcdFile, min_distances_2_V_12_fu_656_p3, "min_distances_2_V_12_fu_656_p3");
    sc_trace(mVcdFile, min_distances_2_V_2_fu_86, "min_distances_2_V_2_fu_86");
    sc_trace(mVcdFile, min_distances_2_V_6_fu_648_p3, "min_distances_2_V_6_fu_648_p3");
    sc_trace(mVcdFile, voters_2_V_1_fu_90, "voters_2_V_1_fu_90");
    sc_trace(mVcdFile, voters_2_V_12_fu_640_p3, "voters_2_V_12_fu_640_p3");
    sc_trace(mVcdFile, voters_2_V_2_fu_94, "voters_2_V_2_fu_94");
    sc_trace(mVcdFile, voters_2_V_9_fu_632_p3, "voters_2_V_9_fu_632_p3");
    sc_trace(mVcdFile, voters_2_V_7_fu_98, "voters_2_V_7_fu_98");
    sc_trace(mVcdFile, voters_2_V_4_fu_624_p3, "voters_2_V_4_fu_624_p3");
    sc_trace(mVcdFile, tmp_11_fu_790_p2, "tmp_11_fu_790_p2");
    sc_trace(mVcdFile, sel_tmp_fu_314_p2, "sel_tmp_fu_314_p2");
    sc_trace(mVcdFile, sel_tmp6_fu_328_p2, "sel_tmp6_fu_328_p2");
    sc_trace(mVcdFile, sel_tmp5_fu_320_p3, "sel_tmp5_fu_320_p3");
    sc_trace(mVcdFile, sel_tmp9_fu_342_p3, "sel_tmp9_fu_342_p3");
    sc_trace(mVcdFile, tmp_7_fu_412_p3, "tmp_7_fu_412_p3");
    sc_trace(mVcdFile, tmp_cast_fu_408_p1, "tmp_cast_fu_408_p1");
    sc_trace(mVcdFile, tmp_14_cast_fu_438_p1, "tmp_14_cast_fu_438_p1");
    sc_trace(mVcdFile, tmp_14_fu_442_p2, "tmp_14_fu_442_p2");
    sc_trace(mVcdFile, tmp_3_fu_464_p5, "tmp_3_fu_464_p5");
    sc_trace(mVcdFile, cond_fu_482_p2, "cond_fu_482_p2");
    sc_trace(mVcdFile, min_distances_V_load_phi_fu_488_p3, "min_distances_V_load_phi_fu_488_p3");
    sc_trace(mVcdFile, ult_fu_496_p2, "ult_fu_496_p2");
    sc_trace(mVcdFile, sel_tmp1_fu_520_p2, "sel_tmp1_fu_520_p2");
    sc_trace(mVcdFile, voters_2_V_fu_526_p3, "voters_2_V_fu_526_p3");
    sc_trace(mVcdFile, voters_2_V_5_fu_542_p3, "voters_2_V_5_fu_542_p3");
    sc_trace(mVcdFile, min_distances_2_V_8_fu_566_p3, "min_distances_2_V_8_fu_566_p3");
    sc_trace(mVcdFile, min_distances_2_V_9_fu_582_p3, "min_distances_2_V_9_fu_582_p3");
    sc_trace(mVcdFile, tmp_20_fu_508_p2, "tmp_20_fu_508_p2");
    sc_trace(mVcdFile, tmp_21_fu_514_p2, "tmp_21_fu_514_p2");
    sc_trace(mVcdFile, tmp_fu_606_p2, "tmp_fu_606_p2");
    sc_trace(mVcdFile, rev_fu_502_p2, "rev_fu_502_p2");
    sc_trace(mVcdFile, tmp_18_fu_476_p2, "tmp_18_fu_476_p2");
    sc_trace(mVcdFile, or_cond_fu_612_p2, "or_cond_fu_612_p2");
    sc_trace(mVcdFile, sel_tmp8_fu_618_p2, "sel_tmp8_fu_618_p2");
    sc_trace(mVcdFile, voters_2_V_3_fu_534_p3, "voters_2_V_3_fu_534_p3");
    sc_trace(mVcdFile, voters_2_V_6_fu_550_p3, "voters_2_V_6_fu_550_p3");
    sc_trace(mVcdFile, voters_2_V_8_fu_558_p3, "voters_2_V_8_fu_558_p3");
    sc_trace(mVcdFile, min_distances_2_V_5_fu_574_p3, "min_distances_2_V_5_fu_574_p3");
    sc_trace(mVcdFile, min_distances_2_V_7_fu_590_p3, "min_distances_2_V_7_fu_590_p3");
    sc_trace(mVcdFile, min_distances_2_V_11_fu_598_p3, "min_distances_2_V_11_fu_598_p3");
    sc_trace(mVcdFile, tmp_1_fu_731_p5, "tmp_1_fu_731_p5");
    sc_trace(mVcdFile, min_dist_V_fu_748_p5, "min_dist_V_fu_748_p5");
    sc_trace(mVcdFile, tmp_12_fu_760_p2, "tmp_12_fu_760_p2");
    sc_trace(mVcdFile, min_voter_V_fu_766_p1, "min_voter_V_fu_766_p1");
    sc_trace(mVcdFile, tmp_30_cast_fu_813_p1, "tmp_30_cast_fu_813_p1");
    sc_trace(mVcdFile, tmp_17_fu_822_p2, "tmp_17_fu_822_p2");
    sc_trace(mVcdFile, tmp_19_fu_828_p2, "tmp_19_fu_828_p2");
    sc_trace(mVcdFile, sel_tmp2_fu_856_p2, "sel_tmp2_fu_856_p2");
    sc_trace(mVcdFile, sel_tmp3_fu_862_p2, "sel_tmp3_fu_862_p2");
    sc_trace(mVcdFile, p_2_agg_result_V_fu_834_p3, "p_2_agg_result_V_fu_834_p3");
    sc_trace(mVcdFile, result_V_1_fu_848_p3, "result_V_1_fu_848_p3");
    sc_trace(mVcdFile, p_2_agg_result_V_load_fu_841_p3, "p_2_agg_result_V_load_fu_841_p3");
    sc_trace(mVcdFile, result_V_3_fu_876_p3, "result_V_3_fu_876_p3");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

dut_knn_vote::~dut_knn_vote() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete votes_V_U;
    delete dut_mux_3to1_sel2_6_1_U5;
    delete dut_mux_3to1_sel2_4_1_U6;
    delete dut_mux_3to1_sel2_6_1_U7;
}

void dut_knn_vote::thread_ap_clk_no_reset_() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        agg_result_V_load_reg_251 = result_V_4_fu_884_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_719_p2.read()))) {
        agg_result_V_load_reg_251 = ap_const_lv4_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        agg_result_V_reg_239 = result_V_2_fu_868_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_719_p2.read()))) {
        agg_result_V_reg_239 = ap_const_lv4_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv4_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) && 
             !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_797_p2.read()))) {
            ap_return_preg = agg_result_V_reg_239.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !esl_seteq<1,1,1>(exitcond2_fu_396_p2.read(), ap_const_lv1_0))) {
        i4_reg_195 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_702_p2.read()))) {
        i4_reg_195 = i_fu_708_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_702_p2.read()))) {
        i5_reg_228 = ap_const_lv2_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        i5_reg_228 = i_4_reg_1008.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_452_p2.read()))) {
        j_reg_172 = j_1_reg_979.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
                esl_seteq<1,1,1>(exitcond2_fu_396_p2.read(), ap_const_lv1_0))) {
        j_reg_172 = ap_const_lv2_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        k2_reg_183 = k_2_reg_992.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_426_p2.read()))) {
        k2_reg_183 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_302_p2.read()))) {
        k_reg_149 = k_1_fu_308_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        k_reg_149 = ap_const_lv2_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        min_distances_2_V_2_fu_86 = min_distances_2_V_6_fu_648_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_302_p2.read()))) {
        min_distances_2_V_2_fu_86 = min_distances_2_V_fu_70.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        min_distances_2_V_3_fu_78 = min_distances_2_V_13_fu_664_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_302_p2.read()))) {
        min_distances_2_V_3_fu_78 = min_distances_0_V_fu_62.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        min_distances_2_V_4_fu_82 = min_distances_2_V_12_fu_656_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_302_p2.read()))) {
        min_distances_2_V_4_fu_82 = min_distances_1_V_fu_66.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_702_p2.read()))) {
        p_1_reg_217 = ap_const_lv6_32;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        p_1_reg_217 = p_1_14_reg_1023.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_702_p2.read()))) {
        p_s_reg_206 = ap_const_lv6_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        p_s_reg_206 = min_voter_V_s_reg_1018.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        result_V_reg_263 = i_V_fu_892_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_719_p2.read()))) {
        result_V_reg_263 = ap_const_lv4_1;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_302_p2.read()))) {
        voters_1_V_reg_160 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_426_p2.read()))) {
        voters_1_V_reg_160 = i_3_reg_966.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        i_3_reg_966 = i_3_fu_402_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        i_4_reg_1008 = i_4_fu_725_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        j_1_reg_979 = j_1_fu_432_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        k_2_reg_992 = k_2_fu_458_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_426_p2.read()))) {
        knn_set_V_addr_reg_984 =  (sc_lv<5>) (tmp_29_cast_fu_447_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_302_p2.read()))) {
        min_distances_0_V_fu_62 = min_distances_0_V_1_fu_358_p3.read();
        min_distances_1_V_fu_66 = min_distances_1_V_1_fu_350_p3.read();
        min_distances_2_V_fu_70 = min_distances_2_V_1_fu_334_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_719_p2.read()))) {
        min_voter_V_s_reg_1018 = min_voter_V_s_fu_770_p3.read();
        p_1_14_reg_1023 = p_1_14_fu_778_p3.read();
        votes_V_addr_1_reg_1013 =  (sc_lv<4>) (tmp_10_fu_743_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_719_p2.read()))) {
        tmp_15_cast_reg_1028 = tmp_15_cast_fu_786_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_797_p2.read()))) {
        tmp_22_reg_1046 = tmp_22_fu_817_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && esl_seteq<1,1,1>(exitcond2_fu_396_p2.read(), ap_const_lv1_0))) {
        tmp_8_reg_971 = tmp_8_fu_420_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        voters_2_V_1_fu_90 = voters_2_V_12_fu_640_p3.read();
        voters_2_V_2_fu_94 = voters_2_V_9_fu_632_p3.read();
        voters_2_V_7_fu_98 = voters_2_V_4_fu_624_p3.read();
    }
}

void dut_knn_vote::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_797_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dut_knn_vote::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dut_knn_vote::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_797_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dut_knn_vote::thread_ap_return() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_797_p2.read()))) {
        ap_return = agg_result_V_reg_239.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void dut_knn_vote::thread_ap_sig_103() {
    ap_sig_103 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void dut_knn_vote::thread_ap_sig_125() {
    ap_sig_125 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(9, 9));
}

void dut_knn_vote::thread_ap_sig_141() {
    ap_sig_141 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(10, 10));
}

void dut_knn_vote::thread_ap_sig_189() {
    ap_sig_189 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void dut_knn_vote::thread_ap_sig_205() {
    ap_sig_205 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void dut_knn_vote::thread_ap_sig_28() {
    ap_sig_28 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void dut_knn_vote::thread_ap_sig_47() {
    ap_sig_47 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void dut_knn_vote::thread_ap_sig_56() {
    ap_sig_56 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void dut_knn_vote::thread_ap_sig_71() {
    ap_sig_71 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void dut_knn_vote::thread_ap_sig_85() {
    ap_sig_85 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void dut_knn_vote::thread_ap_sig_94() {
    ap_sig_94 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void dut_knn_vote::thread_ap_sig_cseq_ST_st10_fsm_9() {
    if (ap_sig_125.read()) {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    }
}

void dut_knn_vote::thread_ap_sig_cseq_ST_st11_fsm_10() {
    if (ap_sig_141.read()) {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    }
}

void dut_knn_vote::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_28.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void dut_knn_vote::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_47.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void dut_knn_vote::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_56.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void dut_knn_vote::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_71.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void dut_knn_vote::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_85.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void dut_knn_vote::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_189.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void dut_knn_vote::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_94.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void dut_knn_vote::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_103.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void dut_knn_vote::thread_ap_sig_cseq_ST_st9_fsm_8() {
    if (ap_sig_205.read()) {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    }
}

void dut_knn_vote::thread_cond_fu_482_p2() {
    cond_fu_482_p2 = (!k2_reg_183.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(k2_reg_183.read() == ap_const_lv2_0);
}

void dut_knn_vote::thread_exitcond1_fu_302_p2() {
    exitcond1_fu_302_p2 = (!k_reg_149.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(k_reg_149.read() == ap_const_lv2_3);
}

void dut_knn_vote::thread_exitcond2_fu_396_p2() {
    exitcond2_fu_396_p2 = (!voters_1_V_reg_160.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(voters_1_V_reg_160.read() == ap_const_lv4_A);
}

void dut_knn_vote::thread_exitcond3_fu_702_p2() {
    exitcond3_fu_702_p2 = (!i4_reg_195.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(i4_reg_195.read() == ap_const_lv4_A);
}

void dut_knn_vote::thread_exitcond4_fu_426_p2() {
    exitcond4_fu_426_p2 = (!j_reg_172.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_172.read() == ap_const_lv2_3);
}

void dut_knn_vote::thread_exitcond5_fu_719_p2() {
    exitcond5_fu_719_p2 = (!i5_reg_228.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(i5_reg_228.read() == ap_const_lv2_3);
}

void dut_knn_vote::thread_exitcond6_fu_452_p2() {
    exitcond6_fu_452_p2 = (!k2_reg_183.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(k2_reg_183.read() == ap_const_lv2_3);
}

void dut_knn_vote::thread_exitcond_fu_797_p2() {
    exitcond_fu_797_p2 = (!result_V_reg_263.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(result_V_reg_263.read() == ap_const_lv4_A);
}

void dut_knn_vote::thread_i_3_fu_402_p2() {
    i_3_fu_402_p2 = (!voters_1_V_reg_160.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(voters_1_V_reg_160.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dut_knn_vote::thread_i_4_fu_725_p2() {
    i_4_fu_725_p2 = (!i5_reg_228.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i5_reg_228.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void dut_knn_vote::thread_i_V_fu_892_p2() {
    i_V_fu_892_p2 = (!result_V_reg_263.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(result_V_reg_263.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dut_knn_vote::thread_i_fu_708_p2() {
    i_fu_708_p2 = (!i4_reg_195.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i4_reg_195.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dut_knn_vote::thread_j_1_fu_432_p2() {
    j_1_fu_432_p2 = (!j_reg_172.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(j_reg_172.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void dut_knn_vote::thread_k_1_fu_308_p2() {
    k_1_fu_308_p2 = (!k_reg_149.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(k_reg_149.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void dut_knn_vote::thread_k_2_fu_458_p2() {
    k_2_fu_458_p2 = (!k2_reg_183.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(k2_reg_183.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void dut_knn_vote::thread_knn_set_V_address0() {
    knn_set_V_address0 = knn_set_V_addr_reg_984.read();
}

void dut_knn_vote::thread_knn_set_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        knn_set_V_ce0 = ap_const_logic_1;
    } else {
        knn_set_V_ce0 = ap_const_logic_0;
    }
}

void dut_knn_vote::thread_min_distances_0_V_1_fu_358_p3() {
    min_distances_0_V_1_fu_358_p3 = (!sel_tmp6_fu_328_p2.read()[0].is_01())? sc_lv<6>(): ((sel_tmp6_fu_328_p2.read()[0].to_bool())? ap_const_lv6_32: min_distances_0_V_fu_62.read());
}

void dut_knn_vote::thread_min_distances_1_V_1_fu_350_p3() {
    min_distances_1_V_1_fu_350_p3 = (!sel_tmp6_fu_328_p2.read()[0].is_01())? sc_lv<6>(): ((sel_tmp6_fu_328_p2.read()[0].to_bool())? min_distances_1_V_fu_66.read(): sel_tmp9_fu_342_p3.read());
}

void dut_knn_vote::thread_min_distances_2_V_11_fu_598_p3() {
    min_distances_2_V_11_fu_598_p3 = (!cond_fu_482_p2.read()[0].is_01())? sc_lv<6>(): ((cond_fu_482_p2.read()[0].to_bool())? knn_set_V_q0.read(): min_distances_2_V_3_fu_78.read());
}

void dut_knn_vote::thread_min_distances_2_V_12_fu_656_p3() {
    min_distances_2_V_12_fu_656_p3 = (!sel_tmp8_fu_618_p2.read()[0].is_01())? sc_lv<6>(): ((sel_tmp8_fu_618_p2.read()[0].to_bool())? min_distances_2_V_7_fu_590_p3.read(): min_distances_2_V_4_fu_82.read());
}

void dut_knn_vote::thread_min_distances_2_V_13_fu_664_p3() {
    min_distances_2_V_13_fu_664_p3 = (!sel_tmp8_fu_618_p2.read()[0].is_01())? sc_lv<6>(): ((sel_tmp8_fu_618_p2.read()[0].to_bool())? min_distances_2_V_11_fu_598_p3.read(): min_distances_2_V_3_fu_78.read());
}

void dut_knn_vote::thread_min_distances_2_V_1_fu_334_p3() {
    min_distances_2_V_1_fu_334_p3 = (!sel_tmp6_fu_328_p2.read()[0].is_01())? sc_lv<6>(): ((sel_tmp6_fu_328_p2.read()[0].to_bool())? min_distances_2_V_fu_70.read(): sel_tmp5_fu_320_p3.read());
}

void dut_knn_vote::thread_min_distances_2_V_5_fu_574_p3() {
    min_distances_2_V_5_fu_574_p3 = (!cond_fu_482_p2.read()[0].is_01())? sc_lv<6>(): ((cond_fu_482_p2.read()[0].to_bool())? min_distances_2_V_2_fu_86.read(): min_distances_2_V_8_fu_566_p3.read());
}

void dut_knn_vote::thread_min_distances_2_V_6_fu_648_p3() {
    min_distances_2_V_6_fu_648_p3 = (!sel_tmp8_fu_618_p2.read()[0].is_01())? sc_lv<6>(): ((sel_tmp8_fu_618_p2.read()[0].to_bool())? min_distances_2_V_5_fu_574_p3.read(): min_distances_2_V_2_fu_86.read());
}

void dut_knn_vote::thread_min_distances_2_V_7_fu_590_p3() {
    min_distances_2_V_7_fu_590_p3 = (!cond_fu_482_p2.read()[0].is_01())? sc_lv<6>(): ((cond_fu_482_p2.read()[0].to_bool())? min_distances_2_V_4_fu_82.read(): min_distances_2_V_9_fu_582_p3.read());
}

void dut_knn_vote::thread_min_distances_2_V_8_fu_566_p3() {
    min_distances_2_V_8_fu_566_p3 = (!sel_tmp1_fu_520_p2.read()[0].is_01())? sc_lv<6>(): ((sel_tmp1_fu_520_p2.read()[0].to_bool())? min_distances_2_V_2_fu_86.read(): knn_set_V_q0.read());
}

void dut_knn_vote::thread_min_distances_2_V_9_fu_582_p3() {
    min_distances_2_V_9_fu_582_p3 = (!sel_tmp1_fu_520_p2.read()[0].is_01())? sc_lv<6>(): ((sel_tmp1_fu_520_p2.read()[0].to_bool())? knn_set_V_q0.read(): min_distances_2_V_4_fu_82.read());
}

void dut_knn_vote::thread_min_distances_V_load_phi_fu_488_p3() {
    min_distances_V_load_phi_fu_488_p3 = (!cond_fu_482_p2.read()[0].is_01())? sc_lv<6>(): ((cond_fu_482_p2.read()[0].to_bool())? min_distances_2_V_4_fu_82.read(): min_distances_2_V_2_fu_86.read());
}

void dut_knn_vote::thread_min_voter_V_fu_766_p1() {
    min_voter_V_fu_766_p1 = esl_zext<6,4>(tmp_1_fu_731_p5.read());
}

void dut_knn_vote::thread_min_voter_V_s_fu_770_p3() {
    min_voter_V_s_fu_770_p3 = (!tmp_12_fu_760_p2.read()[0].is_01())? sc_lv<6>(): ((tmp_12_fu_760_p2.read()[0].to_bool())? min_voter_V_fu_766_p1.read(): p_s_reg_206.read());
}

void dut_knn_vote::thread_or_cond_fu_612_p2() {
    or_cond_fu_612_p2 = (tmp_fu_606_p2.read() | rev_fu_502_p2.read());
}

void dut_knn_vote::thread_p_1_14_fu_778_p3() {
    p_1_14_fu_778_p3 = (!tmp_12_fu_760_p2.read()[0].is_01())? sc_lv<6>(): ((tmp_12_fu_760_p2.read()[0].to_bool())? min_dist_V_fu_748_p5.read(): p_1_reg_217.read());
}

void dut_knn_vote::thread_p_2_agg_result_V_fu_834_p3() {
    p_2_agg_result_V_fu_834_p3 = (!tmp_22_reg_1046.read()[0].is_01())? sc_lv<4>(): ((tmp_22_reg_1046.read()[0].to_bool())? result_V_reg_263.read(): agg_result_V_reg_239.read());
}

void dut_knn_vote::thread_p_2_agg_result_V_load_fu_841_p3() {
    p_2_agg_result_V_load_fu_841_p3 = (!tmp_22_reg_1046.read()[0].is_01())? sc_lv<4>(): ((tmp_22_reg_1046.read()[0].to_bool())? result_V_reg_263.read(): agg_result_V_load_reg_251.read());
}

void dut_knn_vote::thread_result_V_1_fu_848_p3() {
    result_V_1_fu_848_p3 = (!tmp_17_fu_822_p2.read()[0].is_01())? sc_lv<4>(): ((tmp_17_fu_822_p2.read()[0].to_bool())? result_V_reg_263.read(): agg_result_V_reg_239.read());
}

void dut_knn_vote::thread_result_V_2_fu_868_p3() {
    result_V_2_fu_868_p3 = (!sel_tmp3_fu_862_p2.read()[0].is_01())? sc_lv<4>(): ((sel_tmp3_fu_862_p2.read()[0].to_bool())? p_2_agg_result_V_fu_834_p3.read(): result_V_1_fu_848_p3.read());
}

void dut_knn_vote::thread_result_V_3_fu_876_p3() {
    result_V_3_fu_876_p3 = (!tmp_17_fu_822_p2.read()[0].is_01())? sc_lv<4>(): ((tmp_17_fu_822_p2.read()[0].to_bool())? result_V_reg_263.read(): agg_result_V_load_reg_251.read());
}

void dut_knn_vote::thread_result_V_4_fu_884_p3() {
    result_V_4_fu_884_p3 = (!sel_tmp3_fu_862_p2.read()[0].is_01())? sc_lv<4>(): ((sel_tmp3_fu_862_p2.read()[0].to_bool())? p_2_agg_result_V_load_fu_841_p3.read(): result_V_3_fu_876_p3.read());
}

void dut_knn_vote::thread_rev_fu_502_p2() {
    rev_fu_502_p2 = (ult_fu_496_p2.read() ^ ap_const_lv1_1);
}

void dut_knn_vote::thread_sel_tmp1_fu_520_p2() {
    sel_tmp1_fu_520_p2 = (!k2_reg_183.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(k2_reg_183.read() == ap_const_lv2_1);
}

void dut_knn_vote::thread_sel_tmp2_fu_856_p2() {
    sel_tmp2_fu_856_p2 = (tmp_17_fu_822_p2.read() ^ ap_const_lv1_1);
}

void dut_knn_vote::thread_sel_tmp3_fu_862_p2() {
    sel_tmp3_fu_862_p2 = (tmp_19_fu_828_p2.read() & sel_tmp2_fu_856_p2.read());
}

void dut_knn_vote::thread_sel_tmp5_fu_320_p3() {
    sel_tmp5_fu_320_p3 = (!sel_tmp_fu_314_p2.read()[0].is_01())? sc_lv<6>(): ((sel_tmp_fu_314_p2.read()[0].to_bool())? min_distances_2_V_fu_70.read(): ap_const_lv6_32);
}

void dut_knn_vote::thread_sel_tmp6_fu_328_p2() {
    sel_tmp6_fu_328_p2 = (!k_reg_149.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(k_reg_149.read() == ap_const_lv2_0);
}

void dut_knn_vote::thread_sel_tmp8_fu_618_p2() {
    sel_tmp8_fu_618_p2 = (tmp_18_fu_476_p2.read() & or_cond_fu_612_p2.read());
}

void dut_knn_vote::thread_sel_tmp9_fu_342_p3() {
    sel_tmp9_fu_342_p3 = (!sel_tmp_fu_314_p2.read()[0].is_01())? sc_lv<6>(): ((sel_tmp_fu_314_p2.read()[0].to_bool())? ap_const_lv6_32: min_distances_1_V_fu_66.read());
}

void dut_knn_vote::thread_sel_tmp_fu_314_p2() {
    sel_tmp_fu_314_p2 = (!k_reg_149.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(k_reg_149.read() == ap_const_lv2_1);
}

void dut_knn_vote::thread_tmp_10_fu_743_p1() {
    tmp_10_fu_743_p1 = esl_zext<64,4>(tmp_1_fu_731_p5.read());
}

void dut_knn_vote::thread_tmp_11_fu_790_p2() {
    tmp_11_fu_790_p2 = (!votes_V_q0.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(votes_V_q0.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dut_knn_vote::thread_tmp_12_fu_760_p2() {
    tmp_12_fu_760_p2 = (!min_dist_V_fu_748_p5.read().is_01() || !p_1_reg_217.read().is_01())? sc_lv<1>(): (sc_biguint<6>(min_dist_V_fu_748_p5.read()) < sc_biguint<6>(p_1_reg_217.read()));
}

void dut_knn_vote::thread_tmp_14_cast_fu_438_p1() {
    tmp_14_cast_fu_438_p1 = esl_zext<6,2>(j_reg_172.read());
}

void dut_knn_vote::thread_tmp_14_fu_442_p2() {
    tmp_14_fu_442_p2 = (!tmp_8_reg_971.read().is_01() || !tmp_14_cast_fu_438_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_8_reg_971.read()) + sc_biguint<6>(tmp_14_cast_fu_438_p1.read()));
}

void dut_knn_vote::thread_tmp_15_cast_fu_786_p1() {
    tmp_15_cast_fu_786_p1 = esl_zext<7,6>(p_s_reg_206.read());
}

void dut_knn_vote::thread_tmp_15_fu_803_p1() {
    tmp_15_fu_803_p1 = esl_zext<64,4>(result_V_reg_263.read());
}

void dut_knn_vote::thread_tmp_16_fu_808_p1() {
    tmp_16_fu_808_p1 = esl_zext<64,4>(agg_result_V_load_reg_251.read());
}

void dut_knn_vote::thread_tmp_17_fu_822_p2() {
    tmp_17_fu_822_p2 = (!votes_V_q0.read().is_01() || !votes_V_q1.read().is_01())? sc_lv<1>(): (sc_biguint<4>(votes_V_q0.read()) > sc_biguint<4>(votes_V_q1.read()));
}

void dut_knn_vote::thread_tmp_18_fu_476_p2() {
    tmp_18_fu_476_p2 = (!knn_set_V_q0.read().is_01() || !tmp_3_fu_464_p5.read().is_01())? sc_lv<1>(): (sc_biguint<6>(knn_set_V_q0.read()) < sc_biguint<6>(tmp_3_fu_464_p5.read()));
}

void dut_knn_vote::thread_tmp_19_fu_828_p2() {
    tmp_19_fu_828_p2 = (!votes_V_q0.read().is_01() || !votes_V_q1.read().is_01())? sc_lv<1>(): sc_lv<1>(votes_V_q0.read() == votes_V_q1.read());
}

void dut_knn_vote::thread_tmp_20_fu_508_p2() {
    tmp_20_fu_508_p2 = (!tmp_3_fu_464_p5.read().is_01() || !ap_const_lv6_32.is_01())? sc_lv<1>(): sc_lv<1>(tmp_3_fu_464_p5.read() == ap_const_lv6_32);
}

void dut_knn_vote::thread_tmp_21_fu_514_p2() {
    tmp_21_fu_514_p2 = (!k2_reg_183.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(k2_reg_183.read() == ap_const_lv2_2);
}

void dut_knn_vote::thread_tmp_22_fu_817_p2() {
    tmp_22_fu_817_p2 = (!tmp_30_cast_fu_813_p1.read().is_01() || !tmp_15_cast_reg_1028.read().is_01())? sc_lv<1>(): sc_lv<1>(tmp_30_cast_fu_813_p1.read() == tmp_15_cast_reg_1028.read());
}

void dut_knn_vote::thread_tmp_29_cast_fu_447_p1() {
    tmp_29_cast_fu_447_p1 = esl_sext<64,6>(tmp_14_fu_442_p2.read());
}

void dut_knn_vote::thread_tmp_30_cast_fu_813_p1() {
    tmp_30_cast_fu_813_p1 = esl_zext<7,4>(result_V_reg_263.read());
}

void dut_knn_vote::thread_tmp_7_fu_412_p3() {
    tmp_7_fu_412_p3 = esl_concat<4,2>(voters_1_V_reg_160.read(), ap_const_lv2_0);
}

void dut_knn_vote::thread_tmp_8_fu_420_p2() {
    tmp_8_fu_420_p2 = (!tmp_7_fu_412_p3.read().is_01() || !tmp_cast_fu_408_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_7_fu_412_p3.read()) - sc_biguint<6>(tmp_cast_fu_408_p1.read()));
}

void dut_knn_vote::thread_tmp_9_fu_714_p1() {
    tmp_9_fu_714_p1 = esl_zext<64,4>(i4_reg_195.read());
}

void dut_knn_vote::thread_tmp_cast_fu_408_p1() {
    tmp_cast_fu_408_p1 = esl_zext<6,4>(voters_1_V_reg_160.read());
}

void dut_knn_vote::thread_tmp_fu_606_p2() {
    tmp_fu_606_p2 = (tmp_20_fu_508_p2.read() | tmp_21_fu_514_p2.read());
}

void dut_knn_vote::thread_ult_fu_496_p2() {
    ult_fu_496_p2 = (!knn_set_V_q0.read().is_01() || !min_distances_V_load_phi_fu_488_p3.read().is_01())? sc_lv<1>(): (sc_biguint<6>(knn_set_V_q0.read()) < sc_biguint<6>(min_distances_V_load_phi_fu_488_p3.read()));
}

void dut_knn_vote::thread_voters_2_V_12_fu_640_p3() {
    voters_2_V_12_fu_640_p3 = (!sel_tmp8_fu_618_p2.read()[0].is_01())? sc_lv<4>(): ((sel_tmp8_fu_618_p2.read()[0].to_bool())? voters_2_V_8_fu_558_p3.read(): voters_2_V_1_fu_90.read());
}

void dut_knn_vote::thread_voters_2_V_3_fu_534_p3() {
    voters_2_V_3_fu_534_p3 = (!cond_fu_482_p2.read()[0].is_01())? sc_lv<4>(): ((cond_fu_482_p2.read()[0].to_bool())? voters_2_V_7_fu_98.read(): voters_2_V_fu_526_p3.read());
}

void dut_knn_vote::thread_voters_2_V_4_fu_624_p3() {
    voters_2_V_4_fu_624_p3 = (!sel_tmp8_fu_618_p2.read()[0].is_01())? sc_lv<4>(): ((sel_tmp8_fu_618_p2.read()[0].to_bool())? voters_2_V_3_fu_534_p3.read(): voters_2_V_7_fu_98.read());
}

void dut_knn_vote::thread_voters_2_V_5_fu_542_p3() {
    voters_2_V_5_fu_542_p3 = (!sel_tmp1_fu_520_p2.read()[0].is_01())? sc_lv<4>(): ((sel_tmp1_fu_520_p2.read()[0].to_bool())? voters_1_V_reg_160.read(): voters_2_V_2_fu_94.read());
}

void dut_knn_vote::thread_voters_2_V_6_fu_550_p3() {
    voters_2_V_6_fu_550_p3 = (!cond_fu_482_p2.read()[0].is_01())? sc_lv<4>(): ((cond_fu_482_p2.read()[0].to_bool())? voters_2_V_2_fu_94.read(): voters_2_V_5_fu_542_p3.read());
}

void dut_knn_vote::thread_voters_2_V_8_fu_558_p3() {
    voters_2_V_8_fu_558_p3 = (!cond_fu_482_p2.read()[0].is_01())? sc_lv<4>(): ((cond_fu_482_p2.read()[0].to_bool())? voters_1_V_reg_160.read(): voters_2_V_1_fu_90.read());
}

void dut_knn_vote::thread_voters_2_V_9_fu_632_p3() {
    voters_2_V_9_fu_632_p3 = (!sel_tmp8_fu_618_p2.read()[0].is_01())? sc_lv<4>(): ((sel_tmp8_fu_618_p2.read()[0].to_bool())? voters_2_V_6_fu_550_p3.read(): voters_2_V_2_fu_94.read());
}

void dut_knn_vote::thread_voters_2_V_fu_526_p3() {
    voters_2_V_fu_526_p3 = (!sel_tmp1_fu_520_p2.read()[0].is_01())? sc_lv<4>(): ((sel_tmp1_fu_520_p2.read()[0].to_bool())? voters_2_V_7_fu_98.read(): voters_1_V_reg_160.read());
}

void dut_knn_vote::thread_votes_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        votes_V_address0 = votes_V_addr_1_reg_1013.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        votes_V_address0 =  (sc_lv<4>) (tmp_9_fu_714_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        votes_V_address0 =  (sc_lv<4>) (tmp_15_fu_803_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        votes_V_address0 =  (sc_lv<4>) (tmp_10_fu_743_p1.read());
    } else {
        votes_V_address0 = "XXXX";
    }
}

void dut_knn_vote::thread_votes_V_address1() {
    votes_V_address1 =  (sc_lv<4>) (tmp_16_fu_808_p1.read());
}

void dut_knn_vote::thread_votes_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()))) {
        votes_V_ce0 = ap_const_logic_1;
    } else {
        votes_V_ce0 = ap_const_logic_0;
    }
}

void dut_knn_vote::thread_votes_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        votes_V_ce1 = ap_const_logic_1;
    } else {
        votes_V_ce1 = ap_const_logic_0;
    }
}

void dut_knn_vote::thread_votes_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        votes_V_d0 = tmp_11_fu_790_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        votes_V_d0 = ap_const_lv4_0;
    } else {
        votes_V_d0 = "XXXX";
    }
}

void dut_knn_vote::thread_votes_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_702_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()))) {
        votes_V_we0 = ap_const_logic_1;
    } else {
        votes_V_we0 = ap_const_logic_0;
    }
}

void dut_knn_vote::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_302_p2.read())) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        case 4 : 
            if (esl_seteq<1,1,1>(exitcond2_fu_396_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_st7_fsm_6;
            }
            break;
        case 8 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_426_p2.read())) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            }
            break;
        case 16 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_452_p2.read())) {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 64 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_702_p2.read())) {
                ap_NS_fsm = ap_ST_st7_fsm_6;
            } else {
                ap_NS_fsm = ap_ST_st8_fsm_7;
            }
            break;
        case 128 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_719_p2.read())) {
                ap_NS_fsm = ap_ST_st10_fsm_9;
            } else {
                ap_NS_fsm = ap_ST_st9_fsm_8;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
            break;
        case 512 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_797_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st11_fsm_10;
            }
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<11>) ("XXXXXXXXXXX");
            break;
    }
}

}

